// Carta de Fenicia (extraída de fenicia.es). Precios en euros.
// t: veg | picante | sinlactosa · o: opciones (variaciones) · ld: solo de lunes a viernes
window.MENU = [{"id":56,"n":"Menú del día","items":[{"id":2682,"n":"Menú del día","d":"Un combinado a elegir, pan, bebida, postre (según existencia)","p":23.0,"img":"img/shawarma-fenicia-300x300.jpg","ld":1}]},
{"id":19,"n":"Entrantes Fríos","items":[{"id":291,"n":"Baba Ghanouj","d":"Escalivada de berenjenas asadas, pimiento rojo y verde, menta, cebolla, tomate y perejil.","p":8.9,"img":"img/baba-ghanouj-300x300.jpg","t":["veg"]},
{"id":295,"n":"Gebne","d":"Trocitos de pan pita frito con queso feta, cebolla, perejil, tomate y aceite de oliva.","p":9.0,"img":"img/gebne-300x300.jpg","t":["veg"]},
{"id":285,"n":"Hummus","d":"Garbanzos molidos con crema de sésamo.","p":8.45,"img":"img/hummus-fenicia-300x300.jpg","t":["veg"]},
{"id":287,"n":"Hummus Akhdar","d":"Garbanzos molidos con crema de sésamo y hierbabuena triturada, decorado con nueces molidas.","p":8.4,"t":["veg"]},
{"id":286,"n":"Hummus Beiruty","d":"Garbanzos molidos con crema de sésamo, cebolla, tomate y un toque de perejil.","p":8.75,"img":"img/hummus-beiruty-300x300.jpg","t":["veg"]},
{"id":296,"n":"Itch","d":"Sémola de trigo mezclada con pimiento verde y rojo, cebolla, aceite de oliva, limón y un toque de picante","p":7.9,"img":"img/Itch-300x300.jpg","t":["veg","picante"]},
{"id":289,"n":"Labne","d":"Yogurt concentrado con aceite y menta seca.","p":8.5,"img":"img/Labne-300x300.jpg","t":["veg"]},
{"id":290,"n":"Labne Mtabale","d":"Deliciosa crema de yogur mezclada con aceitunas negras, tomate y tomillo libanés.","p":9.0,"img":"img/labne-mtabale-300x300.jpg","t":["veg"]},
{"id":294,"n":"Mohamara","d":"Triturado de nueces, pimiento rojo, pan rallado, zumo de granada y un toque de picante.","p":9.25,"img":"img/mohamara-300x300.jpg","t":["veg","picante"]},
{"id":2246,"n":"Mussaka","d":"","p":9.25,"img":"img/Musaka-300x225.jpeg","t":["veg"]},
{"id":292,"n":"Mutabal","d":"Berenjenas molidas con crema de sésamo.","p":8.45,"img":"img/mutabal-300x300.jpg","t":["veg"]},
{"id":293,"n":"Mutabal Beiruty","d":"Berenjenas molidas con crema de sésamo, cebolla, tomate y un toque de perejil.","p":8.75,"img":"img/mutabal-beiruty-300x300.jpg","t":["veg"]},
{"id":3822,"n":"Pan Libanés Blanco – 12 unidades","d":"","p":8.5,"img":"img/pan-libanes-300x300.jpg","t":["veg"]},
{"id":2189,"n":"Pan Libanés Blanco – 6 unidades","d":"","p":5.0,"img":"img/pan-libanes-300x300.jpg","t":["veg"]},
{"id":3825,"n":"Pan Libanés Integral – 12 unidades","d":"","p":8.5,"img":"img/pan-libanes-300x300.jpg","t":["veg"]},
{"id":3827,"n":"Pan Libanés Integral – 6 unidades","d":"","p":5.0,"img":"img/pan-libanes-300x300.jpg","t":["veg"]},
{"id":2595,"n":"Tamriye","d":"Deliciosa mezcla de dátiles molidos, cebolla cocida mezclados con salsa Tahini y yogur natural","p":9.0,"img":"img/tamriye-300x225.jpeg","t":["veg"]},
{"id":288,"n":"Zalziki","d":"Yogurt con pepino y hierbabuena.","p":8.9,"img":"img/zalziki-300x300.jpg","t":["veg"]}]},
{"id":20,"n":"Entrantes Calientes","items":[{"id":301,"n":"Arroz","d":"Arroz libanés con fideos y frutos secos.","p":5.5,"img":"img/arròs-300x300.jpg","t":["veg"]},
{"id":303,"n":"Batata Harra","d":"Dados de patata frita y mezclados con coriandro natural, ajo y un toque de picante.","p":8.5,"img":"img/batata-harra-300x300.jpg","t":["veg","picante"]},
{"id":304,"n":"Batinjen","d":"Con rodajas de berenjena","p":8.5,"img":"img/Batinjen-300x300.jpg","t":["veg"]},
{"id":299,"n":"Bemye Bil Zeit","d":"Okra cocida con salsa de tomate, aceite, ajo y cebolla","p":8.3,"img":"img/Bemye-Bi-I-Zeit-300x300.jpg","t":["veg"]},
{"id":302,"n":"Falafel (5 unidades)","d":"Croquetas fritas de garbanzos y verduras molidas.","p":8.5,"img":"img/falafel-300x300.jpg","t":["veg"]},
{"id":300,"n":"Foul Moudamas","d":"Habas al estilo libanés, ajo, tomate perejil, limón y aceite.","p":8.3,"img":"img/Foul-moudamas-300x300.jpg","t":["veg"]},
{"id":305,"n":"Kousa","d":"Rodajas de calabacín fritas con salsa de sésamo y un toque de perejil.","p":8.5,"img":"img/kousa-300x300.jpg","t":["veg"]},
{"id":298,"n":"Lubie Bil Zeit","d":"Judías verdes cocidas con salsa de tomate, aceite, ajo y cebolla.","p":8.3,"img":"img/lubie-bil-zeit-300x300.jpg","t":["veg"]},
{"id":297,"n":"Warak Inab Bil Zeit","d":"Hojas de parra rellenas de arroz en aceite.","p":9.4,"img":"img/Warak-inab-300x300.jpg","t":["veg"]}]},
{"id":23,"n":"Platos combinados","items":[{"id":1163,"n":"Arayes Plato Combinado","d":"Todos los platos se sirven con hummus, mutabal, falafel y ensalada verde","p":16.7,"img":"img/arayes-2-300x300.jpg","o":[{"id":1169,"l":"Kafta","p":18.4},
{"id":1170,"l":"Mixto","p":18.4},
{"id":1166,"l":"Especial","p":18.4},
{"id":1167,"l":"Espinacas","p":18.4},
{"id":1172,"l":"Toshka","p":18.4},
{"id":1165,"l":"Calage","p":18.4},
{"id":1168,"l":"Feta","p":18.4},
{"id":1173,"l":"Za'atar","p":18.4},
{"id":1179,"l":"Mshakal jebne","p":16.7},
{"id":1174,"l":"Za'atar con queso","p":18.4},
{"id":1171,"l":"Mohamra","p":18.4}]},
{"id":322,"n":"Kafta","d":"Carne picada, perejil, cebolla y especias.","p":18.7,"img":"img/kafta-300x300.jpg"},
{"id":323,"n":"Kafta Fenicia","d":"Kafta con cebolla y tomate a la plancha.","p":18.8,"img":"img/kafta-fenicia-300x300.jpg"},
{"id":319,"n":"Shawarma","d":"","p":18.4,"img":"img/shawarma-300x300.jpg"},
{"id":320,"n":"Shawarma Fenicia","d":"Shawarma con cebolla y tomate a la plancha","p":18.8,"img":"img/shawarma-fenicia-300x300.jpg"},
{"id":321,"n":"Shish Tawouk","d":"Pinchos de pollo con especias a la plancha","p":18.7,"img":"img/shish-tawouk-300x300.jpg"},
{"id":324,"n":"Súper Carne","d":"Shawarma, kafta, shish tawouk, arayes y kebbe.","p":23.0,"img":"img/Super-carne-300x300.jpg"},
{"id":337,"n":"Toshka","d":"","p":18.4,"img":"img/arayes-2-300x300.jpg"},
{"id":325,"n":"Vegetal","d":"Ensalada verde, hummus, mutabal, zalziki, mussaka, baba ghanouj, falafel y warak inab.","p":19.4,"img":"img/vegetal-300x300.jpg","t":["veg"]}]},
{"id":41,"n":"Arayes","items":[{"id":1297,"n":"Arayes","d":"Pan de pita relleno.","p":7.6,"img":"img/arayes-300x300.jpg","o":[{"id":1298,"l":"Calage","p":7.6},
{"id":1299,"l":"Especial","p":8.3},
{"id":1300,"l":"Espinacas","p":7.6},
{"id":1301,"l":"Feta","p":8.2},
{"id":1302,"l":"Kafta","p":7.9},
{"id":1303,"l":"Mixto","p":8.1},
{"id":1304,"l":"Mohamra","p":8.8},
{"id":1305,"l":"Mshakal jebne","p":8.2},
{"id":1306,"l":"Toshka","p":8.3},
{"id":1307,"l":"Za'atar","p":8.3},
{"id":1308,"l":"Za'atar con queso","p":8.3}]}]},
{"id":21,"n":"Carne","items":[{"id":308,"n":"Hummus Bil Lahme","d":"Garbanzos molidos con crema de sésamo y carne de ternera picada, decorado con frutos secos.","p":11.25,"img":"img/hummus-bil-lahme-300x300.jpg"},
{"id":309,"n":"Kafta bel Saynye","d":"Rodajas de carne de ternera picada al horno con rodajas de tomate y patata, servido con arroz.","p":17.1,"img":"img/kafta-bel-saynye-1-300x300.jpg"},
{"id":310,"n":"Kafta Kheskash","d":"Carne de ternera a la plancha picante con pimiento verde y rojo, tomate y cebolla, servido con arroz.","p":17.1,"img":"img/Kafta-kheshkhash-300x300.jpeg","t":["picante"]},
{"id":306,"n":"Kebbe","d":"4 Croquetas de trigo rellenas de carne picada, cebolla.","p":13.9,"img":"img/kebbe-300x300.jpg"},
{"id":307,"n":"Mussaka de Carne","d":"Berenjenas y patatas cocidas con tomate, carne picada y bechamel al horno","p":13.9,"img":"img/mussaka-de-carn-300x300.jpg"}]},
{"id":46,"n":"Cus-cus","items":[{"id":1275,"n":"Cus-cus Carne","d":"Sin lactosa","p":17.1,"img":"img/cuscus-carne-300x300.jpeg","t":["sinlactosa"]},
{"id":1277,"n":"Cus-cus Mixto","d":"Sin lactosa","p":17.25,"img":"img/mixto-cus-cus-300x300.jpg","t":["sinlactosa"]},
{"id":1273,"n":"Cus-cus Pollo","d":"Sin lactosa","p":17.1,"img":"img/pollo-cus-cus-300x300.jpg","t":["sinlactosa"]},
{"id":1271,"n":"Cus-cus Vegetal","d":"Sin lactosa, vegetariana","p":16.3,"img":"img/vegetal-cus-cus-300x300.jpg","t":["veg","sinlactosa"]}]},
{"id":44,"n":"Ensaladas","items":[{"id":1257,"n":"Arabiye","d":"Picado de zanahoria, pepino, pimiento rojo y verde, lechuga, tomate y cebolla.","p":9.85,"img":"img/arabiye-300x300.jpg","t":["veg"]},
{"id":1249,"n":"Batata Masloua","d":"Patata hervida con perejil, hierbabuena ajo y aceite de oliva.","p":9.85,"img":"img/Batata-masloua-300x300.jpeg","t":["veg"]},
{"id":1253,"n":"Ensalada Griega","d":"Lechuga, tomate, cebolla, olivas, salsa amarilla y queso feta.","p":9.85,"img":"img/grega-300x300.jpg","t":["veg"]},
{"id":1247,"n":"Fatoush","d":"Ensalada libanesa, lechuga, tomate, pimiento rojo y verde, cebolla, pan de pita tostado, pepino, limón y aceite de oliva.","p":9.85,"img":"img/fatoush-300x300.jpg","t":["veg"]},
{"id":1255,"n":"Fenicia","d":"Tomate, cebolla, menta, pepino, pimiento rojo y verde, lechuga, tomate y cebolla.","p":9.85,"img":"img/fenicia-ensalada-300x300.jpg","t":["veg"]},
{"id":1251,"n":"Feta","d":"Lechuga, cebolla, tomate, orégano, queso feta y pan árabe frito.","p":9.85,"img":"img/ensalada-feta-1-300x300.jpg","t":["veg"]},
{"id":1245,"n":"Tabule","d":"Ensalada refrescante a base de perejil con un toque de sémola de trigo, tomate y cebolla. Aliñada con limón y…","p":9.85,"img":"img/tabule-300x300.jpg","t":["veg"]}]},
{"id":42,"n":"Fatayer","items":[{"id":1229,"n":"Empanadillas de Carne","d":"Empanadillas de carne (4 unidades)","p":10.0,"img":"img/Fatayer-carne-300x300.jpg"},
{"id":1233,"n":"Empanadillas de Espinacas","d":"Empanadillas de espinacas (4 unidades)","p":10.0,"img":"img/empanadillas-de-espinacas-300x300.jpg","t":["veg"]},
{"id":1231,"n":"Empanadillas de Queso","d":"Empanadillas de queso (4 unidades)","p":10.0,"img":"img/empanadillas-de-queso-300x300.jpg","t":["veg"]},
{"id":1223,"n":"Rollitos de carne","d":"","p":10.4,"img":"img/rollitos-300x300.jpg"},
{"id":1221,"n":"Rollitos de pollo","d":"","p":10.4,"img":"img/rollitos-300x300.jpg"},
{"id":1227,"n":"Rollitos de queso","d":"","p":10.4,"img":"img/rollitos-300x300.jpg","t":["veg"]},
{"id":1225,"n":"Rollitos de Verduras","d":"Rollitos de verduras","p":10.4,"img":"img/rollitos-300x300.jpg","t":["veg"]}]},
{"id":43,"n":"Fattet","items":[{"id":1243,"n":"Fattet Batinjen","d":"Con rodajas de berenjena y carne picada.","p":15.5,"img":"img/Fattet-batinjen--300x300.jpg"},
{"id":1235,"n":"Fattet Fenicia","d":"Garbanzos hervidos con pan frito y salsa de yogurt y frutos secos.","p":13.95,"img":"img/Fattet-Fenicia-dos-300x300.jpg","t":["veg"]},
{"id":1237,"n":"Fattet Lahme","d":"Con carne picada.","p":15.75,"img":"img/Fattet-lahme-300x300.jpg"},
{"id":1241,"n":"Fattet Pollo y Champiñones","d":"Con pollo asado y champiñones","p":15.95,"img":"img/Fattet-pollo-y-champiñones-300x300.jpg"},
{"id":1239,"n":"Fattet Pollo","d":"Con pollo asado.","p":15.75,"img":"img/Fattet-Batinjen-dos-300x300.jpg"}]},
{"id":45,"n":"Platos cocidos","items":[{"id":1263,"n":"Bazela","d":"Guisantes con zanahoria cocidos con carne de ternera, ajo, salsa de tomate y especias.","p":16.95,"img":"img/bazela-300x300.jpg"},
{"id":1265,"n":"Bemye","d":"Okra con carne de ternera cocida con ajo y salsa de tomate servido con arroz.","p":16.95,"img":"img/Bemye-300x225.jpeg"},
{"id":1267,"n":"Dawud Basha","d":"Albóndigas de carne picada con patatas, salsa de tomate al horno servido con arroz.","p":16.95,"img":"img/dawud-basha-1-300x300.jpg"},
{"id":1261,"n":"Fasolia","d":"Alubias cocidas con carne de ternera, ajo, salsa de tomate y especias.","p":16.95,"img":"img/Fasolia-300x300.jpg"},
{"id":1269,"n":"Lubie","d":"Judías verdes cocidas con carne de ternera, ajo, salsa de tomate y especias.","p":16.95,"img":"img/lubie-300x300.jpg"},
{"id":1259,"n":"Tegin Libanés","d":"Carne de ternera cocida con ajo, salsa de tomate y especias.","p":15.7,"img":"img/tegin-libanes-300x300.jpg"}]},
{"id":22,"n":"Pollo","items":[{"id":318,"n":"Dajaj Bil Sayniye","d":"Deliciosos muslos de pollo al horno con patata y salsa de ajo y limón, servido con arroz libanés.","p":17.25,"img":"img/dajaj-bil-sayniye-300x300.jpg"},
{"id":311,"n":"Jawaneh","d":"Alitas de pollo con salsa amarilla.","p":15.9,"img":"img/Jawaneh-fenicia-300x300.jpg"},
{"id":312,"n":"Jawaneh Fenicia","d":"Alitas de pollo fritas con guarnición de sofrito de cebolla y tomate. Servido con arroz.","p":15.5,"img":"img/jawaneh-fenicia-300x300.jpg"},
{"id":316,"n":"Jawaneh Meliye","d":"Alas de pollo rebozadas y fritas, servidas con salsa de yogurt","p":14.85,"img":"img/Jawaneh-meliye-300x300.jpg"},
{"id":313,"n":"Pollo Especial Fenicia","d":"Muslos de pollo al horno con una deliciosa salsa de nueces y zumo de granada. Servido con arroz.","p":16.5,"img":"img/pollo-especial-fenicia-300x300.jpg"},
{"id":317,"n":"Rezz a Dajaj","d":"Arroz con frutos secos con tiras de pollo encima, servido con yogur.","p":16.1,"img":"img/rezz-a-dajaj-300x300.jpg"},
{"id":314,"n":"Safayen Dajaj","d":"Tiras de pollo a la plancha con salsa amarilla. Servido con arroz libanés","p":16.1,"img":"img/safayen-dajaj-300x300.jpg"},
{"id":315,"n":"Safayen Meliye","d":"Tiras de pollo rebozadas y fritas, servidas con salsa de yogurt.","p":15.1,"img":"img/Safayen-meliye-300x300.jpg"}]},
{"id":49,"n":"Bebidas","items":[{"id":2179,"n":"Aquarius Limón","d":"","p":2.1,"img":"img/aquarius-300x300.jpg"},
{"id":2181,"n":"Aquarius Naranja","d":"","p":2.1,"img":"img/aquarius-naranja-300x300.jpg"},
{"id":2605,"n":"Ayran","d":"Deliciosa bebida de yogur natural, perfecta para platos de carne","p":2.3,"img":"img/Ayran-yogur-300x225.jpeg"},
{"id":2187,"n":"Cerveza Libanesa Beirut","d":"","p":2.9,"img":"img/beirut-300x300.jpg"},
{"id":346,"n":"Clos Dels Angels 2010","d":"","p":20.5},
{"id":2167,"n":"Coca Cola","d":"","p":2.1,"img":"img/cocacola-300x300.jpg"},
{"id":2170,"n":"Coca Cola Zero","d":"","p":2.1,"img":"img/cocacolazero-300x300.jpg"},
{"id":2183,"n":"Estrella Voll Damm","d":"","p":2.1,"img":"img/strellavoldan-300x300.jpg"},
{"id":342,"n":"Fakra Blanco (Blanc de Blancs) 3/4L","d":"","p":18.9},
{"id":341,"n":"Fakra Rosado (la fleur) 3/4L","d":"","p":18.9},
{"id":339,"n":"Fakra Tinto (cuvée du temple) 3/4L","d":"","p":18.9},
{"id":340,"n":"Fakra Tinto (cuvée du temple) 3/8L","d":"","p":10.0},
{"id":2174,"n":"Fanta Limón","d":"","p":2.1,"img":"img/fanta-limon-300x300.jpg"},
{"id":2171,"n":"Fanta Naranja","d":"","p":2.1,"img":"img/fanta-naranja-300x300.jpg"},
{"id":343,"n":"Lopez De Haro (crianza)","d":"","p":22.1},
{"id":2177,"n":"Nestea","d":"","p":2.1,"img":"img/nestea-limon-300x300.jpg"},
{"id":348,"n":"Prado Del Rey (joven roble)","d":"","p":24.2},
{"id":344,"n":"Puerta Vieja (reserva)","d":"","p":22.1},
{"id":345,"n":"Sumarroca Joven","d":"","p":18.9},
{"id":347,"n":"Taneo (joven roble)","d":"","p":22.6},
{"id":2602,"n":"Té con Hierbabuena","d":"Nuestro delicioso té con hierbabuena ya se puede tomar frío y en casa! 50CL","p":2.3,"img":"img/te-225x300.jpeg"},
{"id":338,"n":"Vino De La Casa 3/4L","d":"","p":10.0}]},
{"id":52,"n":"Salsas","items":[{"id":2462,"n":"Mostaza con mayonesa, limón y tomillo","d":"","p":2.1,"img":"img/Mostaza-con-mayonesalimon-y-tomillo-300x300.jpg"},
{"id":2455,"n":"Salsa picante casera","d":"","p":2.1,"img":"img/Salsa-picante-casera-2-300x300.jpg","t":["picante"]},
{"id":2463,"n":"Tahini, crema de sésamo con limón y sal","d":"","p":2.1,"img":"img/Tahini-crema-de-sesamo-con-limon-y-sal-300x300.jpg"}]},
{"id":47,"n":"Postres","items":[{"id":1291,"n":"Baklawa Avellana con chocolate","d":"","p":2.1,"img":"img/avellana-con-chocalate-300x300.jpg"},
{"id":1285,"n":"Baklawa Almendra con chocolate blanco","d":"","p":2.1,"img":"img/baklawa-almendra-con-chocolate-blanco-300x300.jpg"},
{"id":1279,"n":"Baklawa Almendras","d":"","p":2.1,"img":"img/baklawa-almendras-300x300.jpg"},
{"id":1281,"n":"Baklawa Anacardos","d":"","p":2.1,"img":"img/Baklawa-Anacardos-1-300x300.jpg"},
{"id":1289,"n":"Baklawa de Coco","d":"","p":2.1,"img":"img/baklawa-de-coco-300x300.jpg"},
{"id":1293,"n":"Baklawa Nido de Pistacho","d":"","p":2.1,"img":"img/baklawa-nido-de-pistacho-300x300.jpg"},
{"id":1287,"n":"Baklawa Nueces","d":"","p":2.1,"img":"img/baklawa-nueces-300x300.jpg"},
{"id":1283,"n":"Baklawa Pistacho","d":"","p":2.1,"img":"img/baklawa-nido-de-pistacho-300x300.jpg"},
{"id":1295,"n":"Mhalabiye","d":"Deliciosa cuajada al estilo Libanés con agua de azahar y pistachos","p":5.2,"img":"img/mhalabiye-300x300.jpg"},
{"id":2389,"n":"Surtido de baklawa (15 unidades)","d":"","p":9.5,"img":"img/Surtido-de-baklawa-15-unidades-1-300x150.jpeg"}]}];
window.POPULARES = [319, 285, 302, 321, 324, 325, 1247, 297, 292, 1293];
